set_property SRC_FILE_INFO {cfile:{d:/Proyecto Final Digital/corefft UART Block RAM con FFT UartTx 65535/corefft.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc} rfile:../corefft.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc id:1 order:EARLY scoped_inst:CLK/inst} [current_design]
set_property SRC_FILE_INFO {cfile:{D:/Proyecto Final Digital/corefft UART Block RAM con FFT UartTx 65535/corefft.srcs/constrs_1/imports/new/Constraints.xdc} rfile:../corefft.srcs/constrs_1/imports/new/Constraints.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {LEDS[0]}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports {LEDS[1]}]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports {LEDS[2]}]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports {LEDS[3]}]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {LEDS[4]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {LEDS[5]}]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {LEDS[6]}]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports {LEDS2[0]}]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {LEDS2[1]}]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {LEDS2[2]}]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports {LEDS2[3]}]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {LEDS2[4]}]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {LEDS2[5]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS33} [get_ports {LEDS2[6]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[0]}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[7]}]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[10]}]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[15]}]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[18]}]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[20]}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[25]}]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[31]}]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[5]}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[9]}]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[12]}]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[19]}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[21]}]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[24]}]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[28]}]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[13]}]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[1]}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[2]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[3]}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[6]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[8]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[16]}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[22]}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[27]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[29]}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[30]}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[4]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[11]}]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[14]}]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[17]}]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[23]}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/dina[26]}]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[1]}]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[3]}]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[7]}]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[11]}]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[21]}]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[25]}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[27]}]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[6]}]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[14]}]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[15]}]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[17]}]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[18]}]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[24]}]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[28]}]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[29]}]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[2]}]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[0]}]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[4]}]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[10]}]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[13]}]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[16]}]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[23]}]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[30]}]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[31]}]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[5]}]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[8]}]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[9]}]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[12]}]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[19]}]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[20]}]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[22]}]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/doutb[26]}]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/addra[0]}]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/addra[1]}]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/addra[2]}]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/addra[3]}]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/addra[4]}]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/addrb[0]}]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/addrb[1]}]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/addrb[2]}]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/addrb[3]}]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {your_instance_name/addrb[4]}]
